export const SYSTEM_ACTIONS = {
    CASE_CREATED: 'CASE_CREATED',
    PARTY_ADDED: 'PARTY_ADDED',
    PAYMENT_INITIATED: 'PAYMENT_INITIATED',
    PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
    ARBITRATOR_SHORTLISTED: 'ARBITRATOR_SHORTLISTED',
    ARBITRATOR_ACCEPTED: 'ARBITRATOR_ACCEPTED',
    ARBITRATOR_REJECTED: 'ARBITRATOR_REJECTED',
    CASE_STATUS_UPDATED: 'CASE_STATUS_UPDATED',
    CASE_FILED: 'CASE_FILED',
    CASE_DOCUMENTED_ADDED: 'CASE_DOCUMENTED_ADDED',
};
